# Site
title:              Brandon McKinzie
#bio:                ''
description:        "A bit of physics here, and a bit of computer science there."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/Me.jpg'
background:         http://i.imgur.com/oRIhuWM.jpg
tiled_bg:           false
locale:             en_US
url:                http://mckinziebrandon.me

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mckinziebrandon

# Social
email:              mckinziebrandon@berkeley.edu
github:             mckinziebrandon
linkedin:           brandon-mckinzie-452a03112

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
